name: Manual Code Run

# מאפשר להריץ את ה-Action באופן ידני
on:
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      # הגדרת גרסת Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # מוריד את הקוד מהריפו
      - name: Checkout Code
        uses: actions/checkout@v3

      # הדפסת תוכן התיקייה
      - name: List Repository Files
        run: ls -R

      # התקנת תלות (אם יש requirements.txt)
      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # הרצת הקובץ
      - name: Run Script
        run: python main.py
